/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRACE_H_RPCGEN
#define _TRACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char *message;
	int pid;
};
typedef struct data data;


struct reponse {
	int errno;
};
typedef struct reponse reponse;


#define CALCUL 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define TRACE 0
extern  reponse * trace_1(data *, CLIENT *);
extern  reponse * trace_1_svc(data *, struct svc_req *);
extern int calcul_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TRACE 0
extern  reponse * trace_1();
extern  reponse * trace_1_svc();
extern int calcul_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_reponse (XDR *, reponse*);
extern  bool_t xdr_reponse (XDR *, reponse*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();
extern bool_t xdr_reponse ();
extern bool_t xdr_reponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRACE_H_RPCGEN */
