/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trace.h"
#include <time.h>

reponse *
trace_1_svc(data *args, struct svc_req *rqstp)
{
	static reponse result;
	FILE *log = fopen("trace.log", "a");
	if(log < 0) {
		perror("Error file opening");
		result.errno = -1;
		return &result;
	}
	fprintf(log, "%lu : %s\n",(unsigned long)time(NULL), args->message);
	printf("%lu : %s\n",(unsigned long)time(NULL), args->message);
	fclose(log);
	result.errno = 0;
	return &result;
}
