/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trace.h"

void send_rpc_msg(char[], int, pid_t);